# Generated by Django 5.2.8 on 2025-11-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item', max_length=255)),
                ('description', models.TextField(help_text='Description of the item')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the item in US dollars', max_digits=10)),
            ],
        ),
    ]
